### Listar produtos
GET http://localhost:5060/api/consulta/listar

### Cadastrar um produto
POST http://localhost:5060/api/consulta/cadastrar
Content-Type: application/json

{
    "produtoId": "3",
    "Quantidade" : "2"
}