// <auto-generated />
using System;
using EstoqueWebApi.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstoqueWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221001151451_CriacaoBD")]
    partial class CriacaoBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("EstoqueWebApi.Models.CategoriaPrd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CategoriaPrd");
                });

            modelBuilder.Entity("EstoqueWebApi.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaPrdId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProdutoId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPrdId");

                    b.HasIndex("ProdutoId1");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("EstoqueWebApi.Models.Produto", b =>
                {
                    b.Property<string>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Preço")
                        .HasColumnType("REAL");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("EstoqueWebApi.Models.Consulta", b =>
                {
                    b.HasOne("EstoqueWebApi.Models.CategoriaPrd", "CategoriaPrd")
                        .WithMany("Consultas")
                        .HasForeignKey("CategoriaPrdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstoqueWebApi.Models.Produto", "Produto")
                        .WithMany("Consultas")
                        .HasForeignKey("ProdutoId1");

                    b.Navigation("CategoriaPrd");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EstoqueWebApi.Models.CategoriaPrd", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("EstoqueWebApi.Models.Produto", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
